name: CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npx prettier . --check

      - name: Print name
        run: echo "Pipeline executada por Rita Pinto"
